# Generated by Django 3.1.4 on 2020-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosgeldin_mesaji', models.CharField(max_length=250)),
                ('teaser', models.CharField(max_length=250)),
            ],
        ),
    ]
