# Generated by Django 3.1.4 on 2020-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='intro',
            name='teaser',
        ),
    ]
