# Generated by Django 3.1.4 on 2020-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201209_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmetler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis', models.CharField(max_length=500)),
                ('ikinci_el', models.CharField(max_length=500)),
                ('servis', models.CharField(max_length=500)),
                ('ihracat', models.CharField(max_length=500)),
            ],
        ),
    ]
