# Generated by Django 3.1.4 on 2020-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hizmetler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_bir', models.CharField(max_length=200)),
                ('adres_iki', models.CharField(default='İstanbul', max_length=200)),
                ('sabit_tel', models.CharField(default='+90 ', max_length=20)),
                ('mobil_tel', models.CharField(default='+90 ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ekip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekip', models.CharField(max_length=500)),
            ],
        ),
    ]
