# Generated by Django 3.1.4 on 2020-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_adres_ekip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hizmetler',
            old_name='ihracat',
            new_name='yedek_parca',
        ),
    ]
