# Generated by Django 3.1.4 on 2020-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201213_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harita', models.CharField(max_length=3000)),
            ],
        ),
    ]
